- name: "HIGH | V-1073 | AUDIT | Systems must be at supported service packs (SP) or releases levels."
  win_command: true
  register: result
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat1
      - high
      - audit
      - V-1073

- name: "HIGH | V-1073 | PATCH | Systems must be at supported service packs (SP) or releases levels."
  win_command: true
  tags:
      - cat1
      - high
      - patch
      - V-1073

- name: "HIGH | V-1074 | AUDIT | An approved, up-to-date, DoD antivirus program must be installed and used."
  win_command: true
  register: result
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat1
      - high
      - audit
      - V-1074

- name: "HIGH | V-1074 | PATCH | An approved, up-to-date, DoD antivirus program must be installed and used."
  win_command: true
  tags:
      - cat1
      - high
      - patch
      - V-1074

- name: "HIGH | V-1081 | AUDIT | Local volumes are not formatted using NTFS."
  win_command: true
  register: result
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat1
      - high
      - audit
      - V-1081

- name: "HIGH | V-1081 | PATCH | Local volumes are not formatted using NTFS."
  win_command: true
  tags:
      - cat1
      - high
      - patch
      - V-1081

- name: "HIGH | V-1093 | AUDIT | Anonymous shares are not restricted."
  win_command: true
  register: result
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat1
      - high
      - audit
      - V-1093

- name: "HIGH | V-1093 | PATCH | Anonymous shares are not restricted."
  win_command: true
  tags:
      - cat1
      - high
      - patch
      - V-1093

- name: "HIGH | V-1102 | AUDIT | Unauthorized users are granted right to Act as part of the operating system."
  win_command: true
  register: result
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat1
      - high
      - audit
      - V-1102

- name: "HIGH | V-1102 | PATCH | Unauthorized users are granted right to Act as part of the operating system."
  win_command: true
  tags:
      - cat1
      - high
      - patch
      - V-1102

- name: "HIGH | V-1121 | AUDIT | Installed FTP server is configured to allow access to the system drive."
  win_command: true
  register: result
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat1
      - high
      - audit
      - V-1121

- name: "HIGH | V-1121 | PATCH | Installed FTP server is configured to allow access to the system drive."
  win_command: true
  tags:
      - cat1
      - high
      - patch
      - V-1121

- name: "HIGH | V-1127 | AUDIT | Only administrators responsible for the system must have Administrator rights on the system."
  win_command: true
  register: result
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat1
      - high
      - audit
      - V-1127

- name: "HIGH | V-1127 | PATCH | Only administrators responsible for the system must have Administrator rights on the system."
  win_command: true
  tags:
      - cat1
      - high
      - patch
      - V-1127

- name: "HIGH | V-1140 | AUDIT | Users with Administrative privilege are not documented or do not have separate accounts for administrative duties and normal operational tasks."
  win_command: true
  register: result
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat1
      - high
      - audit
      - V-1140

- name: "HIGH | V-1140 | PATCH | Users with Administrative privilege are not documented or do not have separate accounts for administrative duties and normal operational tasks."
  win_command: true
  tags:
      - cat1
      - high
      - patch
      - V-1140

- name: "HIGH | V-1152 | AUDIT | Anonymous access to the registry must be restricted."
  win_command: true
  register: result
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat1
      - high
      - audit
      - V-1152

- name: "HIGH | V-1152 | PATCH | Anonymous access to the registry must be restricted."
  win_command: true
  tags:
      - cat1
      - high
      - patch
      - V-1152

- name: "HIGH | V-1153 | AUDIT | The Send download LanMan compatible password option is not set to Send NTLMv2 response only\refuse LM."
  win_command: true
  register: result
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat1
      - high
      - audit
      - V-1153

- name: "HIGH | V-1153 | PATCH | The Send download LanMan compatible password option is not set to Send NTLMv2 response only\refuse LM."
  win_command: true
  tags:
      - cat1
      - high
      - patch
      - V-1153

- name: "HIGH | V-1159 | AUDIT | The Recovery Console option is set to permit automatic logon to the system."
  win_command: true
  register: result
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat1
      - high
      - audit
      - V-1159

- name: "HIGH | V-1159 | PATCH | The Recovery Console option is set to permit automatic logon to the system."
  win_command: true
  tags:
      - cat1
      - high
      - patch
      - V-1159

- name: "HIGH | V-2374 | AUDIT | The system is configured to autoplay removable media."
  win_command: true
  register: result
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat1
      - high
      - audit
      - V-2374

- name: "HIGH | V-2374 | PATCH | The system is configured to autoplay removable media."
  win_command: true
  tags:
      - cat1
      - high
      - patch
      - V-2374

- name: "HIGH | V-2908 | AUDIT | Unencrypted remote access is permitted to system services."
  win_command: true
  register: result
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat1
      - high
      - audit
      - V-2908

- name: "HIGH | V-2908 | PATCH | Unencrypted remote access is permitted to system services."
  win_command: true
  tags:
      - cat1
      - high
      - patch
      - V-2908

- name: "HIGH | V-3337 | AUDIT | Anonymous SID/Name translation is allowed."
  win_command: true
  register: result
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat1
      - high
      - audit
      - V-3337

- name: "HIGH | V-3337 | PATCH | Anonymous SID/Name translation is allowed."
  win_command: true
  tags:
      - cat1
      - high
      - patch
      - V-3337

- name: "HIGH | V-3338 | AUDIT | Unauthorized named pipes are accessible with anonymous credentials."
  win_command: true
  register: result
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat1
      - high
      - audit
      - V-3338

- name: "HIGH | V-3338 | PATCH | Unauthorized named pipes are accessible with anonymous credentials."
  win_command: true
  tags:
      - cat1
      - high
      - patch
      - V-3338

- name: "HIGH | V-3339 | AUDIT | Unauthorized registry paths are remotely accessible."
  win_command: true
  register: result
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat1
      - high
      - audit
      - V-3339

- name: "HIGH | V-3339 | PATCH | Unauthorized registry paths are remotely accessible."
  win_command: true
  tags:
      - cat1
      - high
      - patch
      - V-3339

- name: "HIGH | V-3340 | AUDIT | Unauthorized shares can be accessed anonymously."
  win_command: true
  register: result
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat1
      - high
      - audit
      - V-3340

- name: "HIGH | V-3340 | PATCH | Unauthorized shares can be accessed anonymously."
  win_command: true
  tags:
      - cat1
      - high
      - patch
      - V-3340

- name: "HIGH | V-3343 | AUDIT | Solicited Remote Assistance is allowed."
  win_command: true
  register: result
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat1
      - high
      - audit
      - V-3343

- name: "HIGH | V-3343 | PATCH | Solicited Remote Assistance is allowed."
  win_command: true
  tags:
      - cat1
      - high
      - patch
      - V-3343

- name: "HIGH | V-3344 | AUDIT | The use of local accounts with blank passwords is not restricted to console logons only."
  win_command: true
  register: result
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat1
      - high
      - audit
      - V-3344

- name: "HIGH | V-3344 | PATCH | The use of local accounts with blank passwords is not restricted to console logons only."
  win_command: true
  tags:
      - cat1
      - high
      - patch
      - V-3344

- name: "HIGH | V-3379 | AUDIT | The system is configured to store the LAN Manager hash of the password in the SAM."
  win_command: true
  register: result
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat1
      - high
      - audit
      - V-3379

- name: "HIGH | V-3379 | PATCH | The system is configured to store the LAN Manager hash of the password in the SAM."
  win_command: true
  tags:
      - cat1
      - high
      - patch
      - V-3379

- name: "HIGH | V-4443 | AUDIT | Unauthorized registry paths and sub-paths are remotely accessible."
  win_command: true
  register: result
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat1
      - high
      - audit
      - V-4443

- name: "HIGH | V-4443 | PATCH | Unauthorized registry paths and sub-paths are remotely accessible."
  win_command: true
  tags:
      - cat1
      - high
      - patch
      - V-4443

- name: "HIGH | V-6834 | AUDIT | Named Pipes and Shares can be accessed anonymously."
  win_command: true
  register: result
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat1
      - high
      - audit
      - V-6834

- name: "HIGH | V-6834 | PATCH | Named Pipes and Shares can be accessed anonymously."
  win_command: true
  tags:
      - cat1
      - high
      - patch
      - V-6834

- name: "HIGH | V-7002 | AUDIT | DoD information system access will require the use of a password."
  win_command: true
  register: result
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat1
      - high
      - audit
      - V-7002

- name: "HIGH | V-7002 | PATCH | DoD information system access will require the use of a password."
  win_command: true
  tags:
      - cat1
      - high
      - patch
      - V-7002

