- name: "File ACL task that works"
  win_acl:
      path: '\Program Files (x86)'
      user: 'BUILTIN\Administrators'
      rights: 'FullControl'
      type: 'allow'
      state: 'present'
      inherit: 'ContainerInherit, ObjectInherit'
      propagation: 'None'

- name: "HIGH | V-1152 | PATCH | Admin Anonymous access to the registry must be restricted."
  win_acl:
      path: 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurePipeServers\Winreg\'
      user: 'BUILTIN\Administrators'
      rights: 'FullControl'
      type: 'allow'
      state: 'present'
      inherit: 'ContainerInherit,ObjectInherit'
      propagation: 'None'
